<?xml version="1.0" encoding="utf-8"?><Database Name="CSDL_Firebase" Class="FCMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=GIANGPHAN;Initial Catalog=CSDL_Firebase;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CSDL_FirebaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FCM" Member="FCMs">
    <Type Name="FCM">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>